name: Tws-Portfolio CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on every push to the 'main' branch

jobs:
  build:
    runs-on: self-hosted  # Running on a self-hosted runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync latest code on self-hosted runner
      run: |
        echo "Pulling the latest code..."
        cd /home/octaloop/tws-portfolio/actions-runner/tws-portfolio  # Ensure this is the correct path to your repo
        git pull origin main  # Pull the latest changes from the 'main' branch

    - name: Set working directory
      run: |
        cd /home/octaloop/tws-portfolio/actions-runner/tws-portfolio  # Change to the project directory

    - name: Build Docker image
      run: |
        docker build --no-cache -t tws-portfolio-image .  # Build the Docker image with the tag 'tws-portfolio-image'

    - name: Check if the container is running, then stop and remove it
      run: |
        if docker ps -q --filter "name=tws-portfolio-container"; then
          echo "Stopping and removing container tws-portfolio-container..."
          docker stop tws-portfolio-container || true  # Stop the container if it's running
          docker rm tws-portfolio-container || true    # Remove the container
        else
          echo "Container tws-portfolio-container is not running. Skipping stop and remove."
        fi

    - name: Run Docker container
      run: |
        docker run -d -p 5173:5173 --name tws-portfolio-container tws-portfolio-image
        # Run the container in detached mode and map port 5173 on the host to port 5173 in the container
